module.exports = {
  ...require('./ui'),
  ...require('./login'),
  ...require('./utils'),
  ...require('./order'),
  ...require('./record'),
  ...require('./roommanager'),
  ...require('./identity'),
  ...require('./livein'),
  ...require('./invoice'),
  ...require('./hotel'),
  ...require('./checkout'),
  ...require('./bill'),
  ...require('./yunba'),
};
